/**
 * @file    Transmitter_40kHz_Generator.ino
 * @brief   Hardware PWM generation at 40kHz using ATmega328P Timer1 Registers
 * @details This code generates a stable 40kHz square wave to drive an L298N 
 * H-Bridge, creating a magnetic field through a wire for proximity sensing.
 */

#define ENA_PIN 9  // Connected to Timer1 - OC1A (Fixed for hardware PWM)
#define IN1_PIN 8  // L298N Direction Control 1
#define IN2_PIN 7  // L298N Direction Control 2

void setup() {
  pinMode(ENA_PIN, OUTPUT);
  pinMode(IN1_PIN, OUTPUT);
  pinMode(IN2_PIN, OUTPUT);

  // Set current direction through the H-Bridge (OUT1 to OUT2)
  digitalWrite(IN1_PIN, HIGH);
  digitalWrite(IN2_PIN, LOW);

  // --- TIMER 1 CONFIGURATION FOR 40kHz FAST PWM ---
  
  // Clear Timer1 Control Registers
  TCCR1A = 0;
  TCCR1B = 0;
  
  // Set Fast PWM Mode (Mode 14), TOP defined by ICR1
  // COM1A1: Non-inverting PWM on Channel A (Pin 9)
  // WGM13, WGM12, WGM11: Fast PWM Mode 14
  TCCR1A = (1 << COM1A1) | (1 << WGM11);
  TCCR1B = (1 << WGM13) | (1 << WGM12) | (1 << CS10); // CS10: Prescaler = 1
  
  // Calculate TOP value for 40kHz frequency
  // Formula: (Clock_Speed / (Prescaler * Target_Frequency)) - 1
  // (16,000,000 / (1 * 40,000)) - 1 = 399
  ICR1 = 399; 

  // --- DUTY CYCLE CONFIGURATION ---
  // Set Duty Cycle to 50% for maximum magnetic induction.
  // 50% of ICR1 (399) is approximately 199.
  OCR1A = 199; 
}

void loop() {
  // PWM signal is generated by hardware in the background.
  // No CPU cycles are required here. The MCU can perform other tasks.
}
